drop table if exists "User";
create table if not exists "User"(
     id bigint generated by default as identity primary key,
     name varchar not null,
     password varchar not null,
     authorised boolean not null
);

drop table if exists "Message";
create table if not exists "Message"(
    id serial primary key,
    room varchar not null,
    author varchar not null,
    text varchar not null,
    datetime timestamp not null
);

drop table if exists "Chatroom";
create table if not exists "Chatroom"(
    id serial primary key,
    name varchar not null,
    owner varchar not null
);